# TorchServe frontend parameters
minWorkers: 1
maxWorkers: 1
maxBatchDelay: 100
responseTimeout: 1200
deviceType: "gpu"
continuousBatching: true

handler:
    model_name: "meta-llama/Llama-2-13b-chat-hf"
    model_path: "model/models--meta-llama--Llama-2-13b-chat-hf/snapshots/0ba94ac9b9e1d5a0037780667e8b219adde1908c"
    max_length: 50
    max_new_tokens: 50
    manual_seed: 40
